
SPECIAL>NOINTERACTION


SPECIAL>LOADMODEL|EthiopiaHCF-V35.mdl
SIMULATE>DATA|"DATA.vdfx"
SIMULATE>ADDCIN|EthiopiaHCF_MC35.out



SIMULATE>RUNNAME|Sens_base_partial
SIMULATE>SETVAL|INITIAL TIME=2007
SIMULATE>SETVAL|FINAL TIME=2027

SIMULATE>SENSITIVITY|MCMC_readfile_partial.vsc
SIMULATE>SENSSAVELIST|Projection_sesitivity_partial.lst
MENU>RUN_SENSITIVITY
MENU>SENS2FILE|Sens_base_partial.vdfx|Sens_base_partial.csv|,*



