
SPECIAL>NOINTERACTION


SPECIAL>LOADMODEL|EthiopiaHCF-V35.mdl
SIMULATE>DATA|"DATA.vdfx"
SIMULATE>ADDCIN|EthiopiaHCF_MC35.out



SIMULATE>RUNNAME|Sens_base
SIMULATE>SETVAL|INITIAL TIME=2007
SIMULATE>SETVAL|FINAL TIME=2027

SIMULATE>SENSITIVITY|MCMC_readfile.vsc
SIMULATE>SENSSAVELIST|Projection_sesitivity.lst
MENU>RUN_SENSITIVITY
MENU>SENS2FILE|Sens_base.vdfx|Sens_base.csv|,*



