
SPECIAL>NOINTERACTION
SPECIAL>LOADMODEL|EthiopiaHCF-V35.mdl
SIMULATE>DATA|"DATA.vdfx"
SIMULATE>ADDCIN|EthiopiaHCF_powell35.out

SIMULATE>SETVAL|INITIAL TIME=2007
SIMULATE>SETVAL|FINAL TIME=2017

SIMULATE>payoff|EthiopianHCF_payoff.vpd
SIMULATE>optparm|EthiopianHCF_powell.voc

SIMULATE>sensitivity|
SIMULATE>savelist|
SIMULATE>senssavelist|



SIMULATE>RUNNAME|EthiopiaHCF_powell35
SIMULATE>REPORT|1
MENU>RUN_OPTIMIZE|o

