
SPECIAL>NOINTERACTION
SPECIAL>LOADMODEL|EthiopiaHCF-V35.mdl
SIMULATE>DATA|"DATA.vdfx"

SIMULATE>SETVAL|INITIAL TIME=2007
SIMULATE>SETVAL|FINAL TIME=2017

SIMULATE>SETVAL|partial cal switch=0

SIMULATE>payoff|EthiopianHCF_payoff.vpd
SIMULATE>optparm|EthiopianHCF_MC_partial.voc

SIMULATE>sensitivity|
SIMULATE>savelist|
SIMULATE>senssavelist|




SIMULATE>RUNNAME|EthiopiaHCF_MC_partial
SIMULATE>REPORT|1
MENU>RUN_OPTIMIZE|o
MENU>VDF2CSV|!|!|


