
SPECIAL>NOINTERACTION


SPECIAL>LOADMODEL|EthiopiaHCF-V35.mdl
SIMULATE>DATA|"DATA.vdfx"




SIMULATE>RUNNAME|Sens_allvars
SIMULATE>SETVAL|INITIAL TIME=2007
SIMULATE>SETVAL|FINAL TIME=2027

SIMULATE>SENSITIVITY|MCMC_readfile.vsc
SIMULATE>SENSSAVELIST|Projection_allvars.lst
MENU>RUN_SENSITIVITY
MENU>SENS2FILE|Sens_allvars.vdfx|Sens_allvars.csv|,*





